parameters:
    ets.document_storage.client.echo_sign.class: ETS\DocumentStorage\Client\EchoSign

services:
    ets.document_storage.client.echo_sign:
        class: %ets.document_storage.client.echo_sign.class%
        arguments:
            - @ets.echo_sign.client
            - @ets.echo_sign.recipient_info_collection
