parameters:
    ets.document_storage.client.echo_sign.class:    ETS\DocumentStorage\Client\EchoSign

    ets.echo_sign.recipient_info_collection.class:  ETS\EchoSignBundle\Api\Parameter\RecipientInfoCollection

services:
    ets.echo_sign.recipient_info_collection:
        class: %ets.echo_sign.recipient_info_collection.class%
        arguments:
            - %ets_contract_echo_sign_recipients%
        public: false

    ets.document_storage.client.echo_sign:
        class: %ets.document_storage.client.echo_sign.class%
        arguments:
            - @ets.echo_sign.client
            - @ets.echo_sign.recipient_info_collection
