parameters:
    aws.s3.client.class: Aws\S3\S3Client
    ets.document_storage.s3.config.region: "eu-west-1"
    ets.document_storage.s3.bucket: "default-bucket"
    ets.document_storage.client.s3.class: ETS\DocumentStorage\Client\S3

services:
    ets.document_storage.client.s3.base:
        class: %aws.s3.client.class%
        factory_class: %aws.s3.client.class%
        factory_method: factory
        arguments:
            - { region: %ets.document_storage.s3.config.region% }
        public: false

    ets.document_storage.client.s3:
        class: %ets.document_storage.client.s3.class%
        arguments:
            - @ets.document_storage.client.s3.base
            - %ets.document_storage.s3.bucket%
