parameters:
    aws.s3.client.class: Aws\S3\S3Client
    ets.document_storage.client.s3.class: ETS\DocumentStorage\Client\S3
    ets.document_storage.s3.config.profile: %kernel.environment%
    ets.document_storage.s3.config.region: "eu-west-1"

services:
    ets.document_storage.client.s3.base:
        class: %aws.s3.client.class%
        factory_class: %aws.s3.client.class%
        factory_method: factory
        arguments:
            - { profile: %ets.document_storage.s3.config.profile%, region: %ets.document_storage.s3.config.region% }
        public: false
