parameters:
    ets.document_storage.client.s3.class: ETS\DocumentStorage\Client\S3
    ets.document_storage.s3.bucket: "default-bucket"

services:
    ets.document_storage.client.s3.base:
        class: %m6web_aws.client.class%
        factory_service: m6web_aws.client_factory
        factory_method: get
        arguments:
            - S3
            - []
        public: false

    ets.document_storage.client.s3:
        class: %ets.document_storage.client.s3.class%
        arguments:
            - @ets.document_storage.client.s3.base
            - %ets.document_storage.s3.bucket%
